### ISSUE TITLE
Minimal R vignette references HELPrct but not included in package.

### ISSUE THREAD

**Issue by SWSRN** [rpruim/mosaic#427]
Minimal R vignette never says you need mosaicData.

**Comment by nicholasjhorton** [comment]
I concur (and in fact encouraged Tanya to make this suggestion).  

I would suggest two changes:

(1) on the Minimal R document commands, include "require(mosaicData)" before the mplot examples, and on the examples page include "require(mosaicData)" before the tally(~ sex + substance, data=HELPrct) 

(2) require(mosaicData) in the next iteration of mosaic (since this problem regularly confuses my students and others).

I realize that (2) was something that we decided against when the package was split out, but I ask that we reconsider.

Nick

P.S. Should we change the "tally(~ x + y)" example to be "tally(y ~ x)"?


> On Feb 27, 2015, at 9:13 AM, SWSRN <notifications@github.com> wrote:
> 
> Minimal R vignette never says you need mosaicData.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment]
`require(mosaicData)` added to Minimal R

The CRAN folks told us not to make mosaicData a dependency.  I don't know whether we can get them to reconsider (or whether they would stop us if we submitted it as a dependency along with a comment indicating that this was a stumbling block for users).

**Comment by rpruim** [comment]
For posterity, here is a portion of the email from CRAN (Kurt Hornik) regarding `mosaic` and `mosaicData`:

```
"Large" is relative to the overall space consumption of current and
previous versions.  In particular we are trying to avoid situations
where changing a few lines of code or docs uses up another 10MB of CRAN
archive space, which can conveniently be dealt with by putting the more
static parts (e.g., data sets or jars) into separate packages.

So assuming that your large data sets are more or less static, pls put
them into a separate package (e.g., mosaicData).

> Pls do *not* use Depends: mosaicData for mosaic.  This will put the data
package on the search path, which is a bad idea.  Instead, use

  Imports: mosaicData

(which will ensure that installing mosaic will trigger installing
mosaicData) and in your NAMESPACE do

  import("mosaicData")

(which will actually import nothing, assuming that mosaicData exports
nothing).

To conveniently access the data sets then from mosaic, you could ensure

  LazyData: true

in mosaicData, and then use mosaicData::foobar to refer to the data
sets.

As already mentioned, it would be great if you could do the split right
away.
```
